site_name: 'MPP Documentation'
repo_url: https://github.com/ShazBSA/rpi-portal-docs
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Tables: tables.md
  - Examples: examples.md
  - Scenarios: scenarios.md
  - Extensions: extensions.md
  - 'Code Sample': code/code-sample.md

plugins:
  - techdocs-core